# Makefile for dagshub-ai-dev-plaform-support
# Generated by AI QuickStart CLI

.DEFAULT_GOAL := help

help:
	@echo "Available targets:"
	@echo ""
	@echo "  setup              Install dependencies for all packages"
	@echo "  dev                Run dev command in each package to start necessary dev servers/containers"
	@echo "  build              Build all packages"
	@echo "  test               Run tests for all packages"
	@echo "  lint               Run linters for all packages"
	@echo "  db-start            Start the database container"
	@echo "  db-stop             Stop the database container"
	@echo "  db-logs             View database container logs"
	@echo "  db-migrate          Run database migrations"
	@echo "  containers-build   Build all container images"
	@echo "  containers-up      Start all containers"
	@echo "  containers-down    Stop all containers"
	@echo "  containers-logs     View logs for all containers"
	@echo "  build-images        Build API and UI container images"
	@echo "  push-images         Push images to OpenShift registry"
	@echo "  deploy             Deploy application using Helm"
	@echo "  deploy-dev          Deploy in development mode"
	@echo "  watch-status        Watch deployment status in real-time (run in separate terminal)"
	@echo "  undeploy            Remove application deployment"
	@echo "  status              Show deployment status"
	@echo "  debug               Show detailed diagnostics for failed deployments"
	@echo "  helm-lint           Lint Helm chart"
	@echo "  helm-template       Render Helm templates"
	@echo "  clean              Remove build artifacts and dependencies"
	@echo ""
	@echo "Deployment Tips:"
	@echo "  - Run 'make watch-status' in another terminal to monitor deployment progress"
	@echo "  - Use 'make status' to check current deployment state"
	@echo "  - Use 'make debug' if deployment fails for detailed diagnostics"
	@echo ""
	@echo "Run 'make <target>' to execute a target"

setup:
	pnpm install
	pnpm -r --if-present install:deps

dev:
	pnpm dev

build:
	pnpm build

test:
	pnpm test

lint:
	pnpm lint

db-start:
	podman-compose up -d dagshub-ai-dev-plaform-support-db

db-stop:
	podman-compose down dagshub-ai-dev-plaform-support-db

db-logs:
	podman-compose logs -f dagshub-ai-dev-plaform-support-db

db-migrate:
	pnpm --filter @*/db migrate

containers-build:
	podman-compose build

containers-up:
	podman-compose up -d

containers-down:
	podman-compose down

containers-logs:
	podman-compose logs -f

clean:
	pnpm clean
	rm -rf node_modules
	rm -rf packages/*/node_modules
	rm -rf packages/*/dist
	rm -rf packages/*/build
	rm -rf packages/*/__pycache__
	rm -rf packages/*/.pytest_cache

build-images:
	@echo "Building API image..."
	@podman build --platform linux/amd64 -f packages/api/Containerfile -t dagshub-ai-dev-plaform-support-api:$(IMAGE_TAG) .
	@echo "Building UI image..."
	@podman build --platform linux/amd64 -f packages/ui/Containerfile -t dagshub-ai-dev-plaform-support-ui:$(IMAGE_TAG) .
	@echo "Building migration image..."
	@podman build --platform linux/amd64 -f packages/db/Containerfile -t dagshub-ai-dev-plaform-support-db:$(IMAGE_TAG) .
	@echo "Building MCP server image..."
	@podman build --platform linux/amd64 -f packages/mcp/Containerfile -t dagshub-ai-dev-plaform-support-mcp:$(IMAGE_TAG) .
	@echo "✅ Images built successfully"

push-images:
	@NEED_BUILD=false && \
	if ! podman image exists dagshub-ai-dev-plaform-support-api:$(IMAGE_TAG); then echo "API image not found"; NEED_BUILD=true; fi && \
	if ! podman image exists dagshub-ai-dev-plaform-support-ui:$(IMAGE_TAG); then echo "UI image not found"; NEED_BUILD=true; fi && \
	if ! podman image exists dagshub-ai-dev-plaform-support-db:$(IMAGE_TAG); then echo "Migration image not found"; NEED_BUILD=true; fi && \
	if ! podman image exists dagshub-ai-dev-plaform-support-mcp:$(IMAGE_TAG); then echo "MCP server image not found"; NEED_BUILD=true; fi && \
	if [ "$$NEED_BUILD" = "true" ]; then echo "Building missing images..."; $(MAKE) build-images; fi && \
	REGISTRY_URL="$(REGISTRY_URL)" && \
	if [ -z "$$REGISTRY_URL" ]; then REGISTRY_URL=$$(oc get route default-route -n openshift-image-registry -o jsonpath='{.spec.host}' 2>/dev/null || echo ""); fi && \
	if [ -z "$$REGISTRY_URL" ]; then CLUSTER_DOMAIN=$$(oc whoami --show-server 2>/dev/null | sed -E 's|https://api\.([^:]+).*|apps.\1|' || echo ""); if [ -n "$$CLUSTER_DOMAIN" ]; then REGISTRY_URL="default-route-openshift-image-registry.$$CLUSTER_DOMAIN"; fi; fi && \
	if [ -z "$$REGISTRY_URL" ]; then echo "Error: Could not detect OpenShift registry URL."; echo "Please set REGISTRY_URL manually: make push-images REGISTRY_URL=your-registry-url"; echo "Or ensure you're logged into OpenShift with 'oc login'"; exit 1; fi && \
	echo "Using registry: $$REGISTRY_URL" && \
	echo "Logging in to registry..." && \
	podman login -u $$(oc whoami) -p $$(oc whoami -t) $$REGISTRY_URL || exit 1 && \
	echo "Ensuring image push permissions..." && \
	oc policy add-role-to-user system:image-builder $$(oc whoami) -n $(NAMESPACE) 2>/dev/null || echo "Permissions may already be set" && \
	echo "Tagging and pushing API image..." && \
	podman tag dagshub-ai-dev-plaform-support-api:$(IMAGE_TAG) $$REGISTRY_URL/$(NAMESPACE)/dagshub-ai-dev-plaform-support-api:$(IMAGE_TAG) && \
	if ! podman push $$REGISTRY_URL/$(NAMESPACE)/dagshub-ai-dev-plaform-support-api:$(IMAGE_TAG); then echo ""; echo "❌ Failed to push API image. Common solutions:"; echo "  1. Ensure you have push permissions: oc policy add-role-to-user system:image-builder $$(oc whoami) -n $(NAMESPACE)"; echo "  2. Check if namespace exists: oc get project $(NAMESPACE)"; echo "  3. Try creating the project: oc new-project $(NAMESPACE)"; exit 1; fi && \
	echo "Tagging and pushing UI image..." && \
	podman tag dagshub-ai-dev-plaform-support-ui:$(IMAGE_TAG) $$REGISTRY_URL/$(NAMESPACE)/dagshub-ai-dev-plaform-support-ui:$(IMAGE_TAG) && \
	if ! podman push $$REGISTRY_URL/$(NAMESPACE)/dagshub-ai-dev-plaform-support-ui:$(IMAGE_TAG); then echo ""; echo "❌ Failed to push UI image. Common solutions:"; echo "  1. Ensure you have push permissions: oc policy add-role-to-user system:image-builder $$(oc whoami) -n $(NAMESPACE)"; echo "  2. Check if namespace exists: oc get project $(NAMESPACE)"; echo "  3. Try creating the project: oc new-project $(NAMESPACE)"; exit 1; fi && \
	echo "Tagging and pushing migration image..." && \
	podman tag dagshub-ai-dev-plaform-support-db:$(IMAGE_TAG) $$REGISTRY_URL/$(NAMESPACE)/dagshub-ai-dev-plaform-support-db:$(IMAGE_TAG) && \
	if ! podman push $$REGISTRY_URL/$(NAMESPACE)/dagshub-ai-dev-plaform-support-db:$(IMAGE_TAG); then echo ""; echo "❌ Failed to push migration image. Common solutions:"; echo "  1. Ensure you have push permissions: oc policy add-role-to-user system:image-builder $$(oc whoami) -n $(NAMESPACE)"; echo "  2. Check if namespace exists: oc get project $(NAMESPACE)"; echo "  3. Try creating the project: oc new-project $(NAMESPACE)"; exit 1; fi && \
	echo "Tagging and pushing MCP server image..." && \
	podman tag dagshub-ai-dev-plaform-support-mcp:$(IMAGE_TAG) $$REGISTRY_URL/$(NAMESPACE)/dagshub-ai-dev-plaform-support-mcp:$(IMAGE_TAG) && \
	if ! podman push $$REGISTRY_URL/$(NAMESPACE)/dagshub-ai-dev-plaform-support-mcp:$(IMAGE_TAG); then echo ""; echo "❌ Failed to push MCP server image. Common solutions:"; echo "  1. Ensure you have push permissions: oc policy add-role-to-user system:image-builder $$(oc whoami) -n $(NAMESPACE)"; echo "  2. Check if namespace exists: oc get project $(NAMESPACE)"; echo "  3. Try creating the project: oc new-project $(NAMESPACE)"; exit 1; fi && \
	echo "✅ Images pushed successfully"

# Deployment configuration
PROJECT_NAME = dagshub-ai-dev-plaform-support
NAMESPACE ?= $(PROJECT_NAME)
REGISTRY_URL ?= $(shell oc get route default-route -n openshift-image-registry -o jsonpath='{.spec.host}' 2>/dev/null || echo "")
REPOSITORY ?= $(PROJECT_NAME)
IMAGE_TAG ?= latest
CLUSTER_DOMAIN ?= $(shell oc whoami --show-server 2>/dev/null | sed -E 's|https://api\.([^:]+).*|apps.\1|' || echo "")
HELM_TIMEOUT ?= 15m
HELM_WAIT ?= --wait
HELM_WAIT_FOR_JOBS ?= --wait-for-jobs

# Default to .env, but allow override
ENV_FILE ?= .env

# Helper function to generate helm parameters from environment variables
define HELM_SECRET_PARAMS
	--set secrets.POSTGRES_DB="$$POSTGRES_DB" \
		--set secrets.POSTGRES_USER="$$POSTGRES_USER" \
		--set secrets.POSTGRES_PASSWORD="$$POSTGRES_PASSWORD" \
		--set pgvector.secret.password="$$POSTGRES_PASSWORD" \
		--set pgvector.secret.user="$$POSTGRES_USER" \
		--set pgvector.secret.dbname="$$POSTGRES_DB" \
		--set secrets.DATABASE_URL="$$DATABASE_URL" \
		--set secrets.DEBUG="$$DEBUG" \
		--set secrets.ALLOWED_HOSTS="$$ALLOWED_HOSTS" \
		--set secrets.VITE_API_BASE_URL="$$VITE_API_BASE_URL" \
		--set secrets.VITE_ENVIRONMENT="$$VITE_ENVIRONMENT" \
		--set secrets.LLM_PROVIDER="$$LLM_PROVIDER" \
		--set secrets.LLM_MODEL="$$LLM_MODEL" \
		--set secrets.LLM_API_KEY="$$LLM_API_KEY" \
		--set secrets.MCP_ENABLED="$$MCP_ENABLED" \
		--set secrets.MCP_SSE_URL="$$MCP_SSE_URL"
endef

# Create OpenShift project/namespace if it doesn't exist
create-project:
	@echo "Checking if project $(NAMESPACE) exists..."
	@if oc get project $(NAMESPACE) >/dev/null 2>&1; then 		echo "⚠️  Project '$(NAMESPACE)' already exists!"; 		echo ""; 		if [ -z "$$SKIP_PROJECT_CHECK" ]; then 			echo "This project may belong to another user or deployment."; 			echo "Do you want to continue deploying to this existing project? (y/N)"; 			read -r response; 			if [ "$$response" != "y" ] && [ "$$response" != "Y" ]; then 				echo "Deployment cancelled."; 				exit 1; 			fi; 		else 			echo "⚠️  Skipping confirmation (SKIP_PROJECT_CHECK is set)"; 		fi; 		echo "Using existing project: $(NAMESPACE)"; 	else 		echo "Creating new project: $(NAMESPACE)"; 		oc new-project $(NAMESPACE) || exit 1; 	fi

# Check and fix stuck Helm releases
check-helm-release:
	@echo "Checking Helm release status..."
	@if helm status $(PROJECT_NAME) --namespace $(NAMESPACE) 2>/dev/null | grep -q "pending-upgrade"; then 		echo "⚠️  Helm release is stuck in 'pending-upgrade' state. Rolling back..."; 		helm rollback $(PROJECT_NAME) --namespace $(NAMESPACE) || echo "Rollback failed or not needed"; 		sleep 2; 	fi || echo "Release check complete"

# Update Helm chart dependencies
helm-dep-update:
	@echo "Updating Helm chart dependencies..."
	@helm dependency update ./deploy/helm/$(PROJECT_NAME) || echo "No dependencies to update"
	@echo "✅ Helm dependencies updated successfully"

# Watch deployment status in real-time (run in separate terminal: make watch-status)
watch-status:
	@echo "Watching deployment status (Ctrl+C to stop)..."
	@watch -n 3 -t bash -c " 		echo '=== '$$(date)' ==='; 		echo ''; 		echo '=== Pod Status ==='; 		oc get pods -n $(NAMESPACE) 2>/dev/null || kubectl get pods -n $(NAMESPACE) 2>/dev/null || echo 'Cannot access pods'; 		echo ''; 		echo '=== Migration Job ==='; 		oc get jobs -n $(NAMESPACE) -l app.kubernetes.io/component=migration 2>/dev/null || kubectl get jobs -n $(NAMESPACE) -l app.kubernetes.io/component=migration 2>/dev/null || echo 'No migration jobs'; 		echo ''; 		echo '=== Recent Events (last 5) ==='; 		oc get events -n $(NAMESPACE) --sort-by='.lastTimestamp' --tail=5 2>/dev/null || kubectl get events -n $(NAMESPACE) --sort-by='.lastTimestamp' --tail=5 2>/dev/null || echo 'Cannot access events'"

# Deploy application with progress monitoring
deploy: create-project check-helm-release build-images push-images helm-dep-update
	@echo "🚀 Deploying application using Helm..."
	@echo ""
	@echo "💡 Tip: Open another terminal and run 'make watch-status' to monitor progress in real-time"
	@echo ""
	@if [ -f "$(ENV_FILE)" ]; then 		set -a; source $(ENV_FILE); set +a; 	fi; 	REGISTRY_URL="$(REGISTRY_URL)"; 	if [ -z "$$REGISTRY_URL" ]; then 		REGISTRY_URL=$$(oc get route default-route -n openshift-image-registry -o jsonpath='{.spec.host}' 2>/dev/null || echo ""); 	fi; 	if [ -z "$$REGISTRY_URL" ]; then 		CLUSTER_DOMAIN=$$(oc whoami --show-server 2>/dev/null | sed -E 's|https://api\.([^:]+).*|apps.\1|' || echo ""); 		if [ -n "$$CLUSTER_DOMAIN" ]; then REGISTRY_URL="default-route-openshift-image-registry.$$CLUSTER_DOMAIN"; fi; 	fi; 	if echo "$$REGISTRY_URL" | grep -q "\.svc:"; then 		REGISTRY_URL=$$(oc get route default-route -n openshift-image-registry -o jsonpath='{.spec.host}' 2>/dev/null || echo "$$REGISTRY_URL"); 	fi; 	echo "📦 Installing/upgrading Helm release..." && 	helm upgrade --install $(PROJECT_NAME) ./deploy/helm/$(PROJECT_NAME) \
		--namespace $(NAMESPACE) \
		--timeout $(HELM_TIMEOUT) \
		$(HELM_WAIT) \
		$(HELM_WAIT_FOR_JOBS) \
		--set global.imageRegistry="$$REGISTRY_URL" \
		--set global.imageRepository=$(REPOSITORY) \
		--set global.imageTag=$(IMAGE_TAG) \
		--set routes.sharedHost="$(PROJECT_NAME)-$(NAMESPACE).$(CLUSTER_DOMAIN)" \
		$(HELM_SECRET_PARAMS) \
		$(HELM_EXTRA_ARGS) && 	echo "" && 	echo "✅ Deployment completed successfully!" && 	echo "" && 	echo "📊 Current status:" && 	$(MAKE) status || (echo ""; echo "❌ Helm deployment failed!"; echo ""; echo "Run 'make debug' for detailed diagnostics or 'make status' for quick status check."; echo ""; $(MAKE) debug; exit 1)

# Deploy in development mode
deploy-dev: create-project check-helm-release build-images push-images helm-dep-update
	@echo "Deploying application in development mode..."
	@if [ -f "$(ENV_FILE)" ]; then 		set -a; source $(ENV_FILE); set +a; 	fi; 	REGISTRY_URL="$(REGISTRY_URL)"; 	if [ -z "$$REGISTRY_URL" ]; then 		REGISTRY_URL=$$(oc get route default-route -n openshift-image-registry -o jsonpath='{.spec.host}' 2>/dev/null || echo ""); 	fi; 	if [ -z "$$REGISTRY_URL" ]; then 		CLUSTER_DOMAIN=$$(oc whoami --show-server 2>/dev/null | sed -E 's|https://api\.([^:]+).*|apps.\1|' || echo ""); 		if [ -n "$$CLUSTER_DOMAIN" ]; then REGISTRY_URL="default-route-openshift-image-registry.$$CLUSTER_DOMAIN"; fi; 	fi; 	if echo "$$REGISTRY_URL" | grep -q "\.svc:"; then 		REGISTRY_URL=$$(oc get route default-route -n openshift-image-registry -o jsonpath='{.spec.host}' 2>/dev/null || echo "$$REGISTRY_URL"); 	fi; 	helm upgrade --install $(PROJECT_NAME) ./deploy/helm/$(PROJECT_NAME) \
		--namespace $(NAMESPACE) \
		--timeout $(HELM_TIMEOUT) \
		$(HELM_WAIT) \
		$(HELM_WAIT_FOR_JOBS) \
		--set global.imageRegistry="$$REGISTRY_URL" \
		--set global.imageRepository=$(REPOSITORY) \
		--set global.imageTag=$(IMAGE_TAG) \
		--set routes.sharedHost="$(PROJECT_NAME)-$(NAMESPACE).$(CLUSTER_DOMAIN)" \
		--set database.persistence.enabled=false \
		--set api.replicas=1 \
		--set ui.replicas=1 \
		$(HELM_SECRET_PARAMS) \
		$(HELM_EXTRA_ARGS) || (echo ""; echo "❌ Helm deployment failed!"; echo ""; echo "Run 'make debug' for detailed diagnostics or 'make status' for quick status check."; echo ""; $(MAKE) debug; exit 1)

# Show deployment status and diagnostics
status:
	@echo "=== Deployment Status ==="
	@helm status $(PROJECT_NAME) --namespace $(NAMESPACE) 2>/dev/null || echo "Release not found"
	@echo ""
	@echo "=== Pod Status ==="
	@oc get pods -n $(NAMESPACE) 2>/dev/null || kubectl get pods -n $(NAMESPACE) 2>/dev/null || echo "Cannot access pods"
	@echo ""
	@echo "=== Services ==="
	@oc get svc -n $(NAMESPACE) 2>/dev/null || kubectl get svc -n $(NAMESPACE) 2>/dev/null || echo "Cannot access services"
	@echo ""
	@echo "=== Migration Job Status ==="
	@oc get jobs -n $(NAMESPACE) -l app.kubernetes.io/component=migration 2>/dev/null || kubectl get jobs -n $(NAMESPACE) -l app.kubernetes.io/component=migration 2>/dev/null || echo "No migration jobs found"
	@echo ""
	@echo "=== Recent Events ==="
	@oc get events -n $(NAMESPACE) --sort-by='.lastTimestamp' --tail=20 2>/dev/null || kubectl get events -n $(NAMESPACE) --sort-by='.lastTimestamp' --tail=20 2>/dev/null || echo "Cannot access events"

# Show detailed diagnostics for failed deployments
debug:
	@echo "=== Helm Release Status ==="
	@helm status $(PROJECT_NAME) --namespace $(NAMESPACE) 2>/dev/null || echo "Release not found or not accessible"
	@echo ""
	@echo "=== Pod Status ==="
	@oc get pods -n $(NAMESPACE) 2>/dev/null || kubectl get pods -n $(NAMESPACE) 2>/dev/null || echo "Cannot access pods"
	@echo ""
	@echo "=== Failed/CrashLoopBackOff Pods ==="
	@FAILED_PODS=$$(oc get pods -n $(NAMESPACE) -o name 2>/dev/null | grep -E "(Failed|CrashLoopBackOff|Error|ImagePullBackOff)" || kubectl get pods -n $(NAMESPACE) -o name 2>/dev/null | grep -E "(Failed|CrashLoopBackOff|Error|ImagePullBackOff)" || echo ""); 	if [ -n "$$FAILED_PODS" ]; then 		oc get pods -n $(NAMESPACE) -o wide 2>/dev/null | grep -E "(Failed|CrashLoopBackOff|Error|ImagePullBackOff)" || kubectl get pods -n $(NAMESPACE) -o wide 2>/dev/null | grep -E "(Failed|CrashLoopBackOff|Error|ImagePullBackOff)" || true; 	else 		echo "No failed pods found"; 	fi
	@echo ""
	@echo "=== Pod Logs (CrashLoopBackOff pods) ==="
	@for pod_name in $$(oc get pods -n $(NAMESPACE) 2>/dev/null | grep CrashLoopBackOff | awk '{print $$1}' || kubectl get pods -n $(NAMESPACE) 2>/dev/null | grep CrashLoopBackOff | awk '{print $$1}' || echo ""); do 		if [ -z "$$pod_name" ]; then echo "No CrashLoopBackOff pods found"; break; fi; 		echo "--- Logs for $$pod_name ---"; 		oc logs -n $(NAMESPACE) $$pod_name --tail=50 2>/dev/null || kubectl logs -n $(NAMESPACE) $$pod_name --tail=50 2>/dev/null || echo "Cannot access logs for $$pod_name"; 		echo ""; 	done
	@echo ""
	@echo "=== Pod Describe (ImagePullBackOff pods) ==="
	@for pod_name in $$(oc get pods -n $(NAMESPACE) 2>/dev/null | grep ImagePullBackOff | awk '{print $$1}' || kubectl get pods -n $(NAMESPACE) 2>/dev/null | grep ImagePullBackOff | awk '{print $$1}' || echo ""); do 		if [ -z "$$pod_name" ]; then echo "No ImagePullBackOff pods found"; break; fi; 		echo "--- Describe $$pod_name ---"; 		oc describe pod -n $(NAMESPACE) $$pod_name 2>/dev/null | tail -40 || kubectl describe pod -n $(NAMESPACE) $$pod_name 2>/dev/null | tail -40 || echo "Cannot describe $$pod_name"; 		echo ""; 	done
	@echo ""
	@echo "=== Recent Events ==="
	@oc get events -n $(NAMESPACE) 2>/dev/null | tail -30 || kubectl get events -n $(NAMESPACE) 2>/dev/null | tail -30 || echo "Cannot access events"
	@echo ""
	@echo "=== Migration Job Status ==="
	@oc get jobs -n $(NAMESPACE) -l app.kubernetes.io/component=migration 2>/dev/null || kubectl get jobs -n $(NAMESPACE) -l app.kubernetes.io/component=migration 2>/dev/null || echo "No migration jobs found"
	@echo ""
	@echo "=== Migration Job Pod Logs ==="
	@MIGRATION_POD=$$(oc get pods -n $(NAMESPACE) -l app.kubernetes.io/component=migration -o name 2>/dev/null | head -1 || kubectl get pods -n $(NAMESPACE) -l app.kubernetes.io/component=migration -o name 2>/dev/null | head -1); 	if [ -n "$$MIGRATION_POD" ]; then 		pod_name=$$(echo $$MIGRATION_POD | sed 's|pod/||'); 		echo "Migration pod: $$pod_name"; 		oc logs -n $(NAMESPACE) $$pod_name --tail=100 2>/dev/null || kubectl logs -n $(NAMESPACE) $$pod_name --tail=100 2>/dev/null || echo "Cannot access migration logs"; 		echo ""; 		oc describe pod -n $(NAMESPACE) $$pod_name 2>/dev/null | tail -40 || kubectl describe pod -n $(NAMESPACE) $$pod_name 2>/dev/null | tail -40 || echo "Cannot describe migration pod"; 	else 		echo "No migration pod found"; 	fi
	@echo ""
	@echo "=== Image Pull Issues ==="
	@oc describe pods -n $(NAMESPACE) 2>/dev/null | grep -B 2 -A 10 -i "imagepull|errimagepull|imagepullbackoff" || kubectl describe pods -n $(NAMESPACE) 2>/dev/null | grep -B 2 -A 10 -i "imagepull|errimagepull|imagepullbackoff" || echo "No image pull errors detected"
	@echo ""
	@echo "=== Troubleshooting Commands ==="
	@echo "  Check all resources: oc get all -n $(NAMESPACE)"
	@echo "  Check Helm status: helm status $(PROJECT_NAME) -n $(NAMESPACE)"
	@echo "  View pod logs: oc logs -n $(NAMESPACE) <pod-name>"
	@echo "  Describe pod: oc describe pod -n $(NAMESPACE) <pod-name>"
	@echo "  Check events: oc get events -n $(NAMESPACE) --sort-by='.lastTimestamp'"
	@echo "  Migration logs: oc logs -n $(NAMESPACE) -l app.kubernetes.io/component=migration"

# Undeploy application
undeploy:
	@echo "🗑️  Undeploying application from $(NAMESPACE)..."
	@echo ""
	@echo "Step 1: Scaling down deployments managed by this Helm release..."
	@oc scale deployment --replicas=0 -n $(NAMESPACE) -l app.kubernetes.io/instance=$(PROJECT_NAME) 2>/dev/null || kubectl scale deployment --replicas=0 -n $(NAMESPACE) -l app.kubernetes.io/instance=$(PROJECT_NAME) 2>/dev/null || echo "No deployments found for this release"
	@echo ""
	@echo "Step 2: Uninstalling Helm release..."
	@helm uninstall $(PROJECT_NAME) --namespace $(NAMESPACE) 2>/dev/null && echo "✅ Helm release uninstalled" || echo "⚠️  Helm release not found or already removed"
	@echo ""
	@echo "Step 3: Cleaning up remaining resources managed by this release..."
	@oc delete job -l app.kubernetes.io/instance=$(PROJECT_NAME) -n $(NAMESPACE) 2>/dev/null || kubectl delete job -l app.kubernetes.io/instance=$(PROJECT_NAME) -n $(NAMESPACE) 2>/dev/null || true
	@oc delete pod -l app.kubernetes.io/instance=$(PROJECT_NAME) -n $(NAMESPACE) 2>/dev/null || kubectl delete pod -l app.kubernetes.io/instance=$(PROJECT_NAME) -n $(NAMESPACE) 2>/dev/null || true
	@echo ""
	@echo "✅ Undeployment complete!"

# Lint Helm chart
helm-lint: helm-dep-update
	@echo "Linting Helm chart..."
	@helm lint ./deploy/helm/$(PROJECT_NAME)

# Render Helm templates
helm-template: helm-dep-update
	@echo "Rendering Helm templates..."
	@if [ -f "$(ENV_FILE)" ]; then \
		set -a; source $(ENV_FILE); set +a; \
	fi; \
	helm template $(PROJECT_NAME) ./deploy/helm/$(PROJECT_NAME) \
		--set global.imageRegistry=$(REGISTRY_URL) \
		--set global.imageRepository=$(REPOSITORY) \
		--set global.imageTag=$(IMAGE_TAG) \
		$(HELM_SECRET_PARAMS)

.PHONY: help setup dev build test lint db-start db-stop db-logs db-migrate containers-build containers-up containers-down containers-logs build-images push-images create-project check-helm-release helm-dep-update watch-status deploy deploy-dev undeploy status debug helm-lint helm-template clean
